"""
    SigniFlow OpenAPI Spec v1

    ## SigniFlow API used to automate esignature workflow creation and management.   # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@signiflow.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import SigniFlowconnect
from SigniFlowconnect.model.full_workflow_request_group_step_field_group_members_field import FullWorkflowRequestGroupStepFieldGroupMembersField
globals()['FullWorkflowRequestGroupStepFieldGroupMembersField'] = FullWorkflowRequestGroupStepFieldGroupMembersField
from SigniFlowconnect.model.full_workflow_request_group_step_field import FullWorkflowRequestGroupStepField


class TestFullWorkflowRequestGroupStepField(unittest.TestCase):
    """FullWorkflowRequestGroupStepField unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFullWorkflowRequestGroupStepField(self):
        """Test FullWorkflowRequestGroupStepField"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FullWorkflowRequestGroupStepField()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
