"""
    SigniFlow OpenAPI Spec v1

    ## SigniFlow API used to automate esignature workflow creation and management.   # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@signiflow.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import SigniFlowconnect
from SigniFlowconnect.model.add_wokflow_step_v2_response_flow_steps_field import AddWokflowStepV2ResponseFlowStepsField
globals()['AddWokflowStepV2ResponseFlowStepsField'] = AddWokflowStepV2ResponseFlowStepsField
from SigniFlowconnect.model.add_wokflow_step_v2_response import AddWokflowStepV2Response


class TestAddWokflowStepV2Response(unittest.TestCase):
    """AddWokflowStepV2Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAddWokflowStepV2Response(self):
        """Test AddWokflowStepV2Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AddWokflowStepV2Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
