"""
    SigniFlow OpenAPI Spec v1

    ## SigniFlow API used to automate esignature workflow creation and management.   # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@signiflow.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import SigniFlowconnect
from SigniFlowconnect.model.token_field import TokenField
globals()['TokenField'] = TokenField
from SigniFlowconnect.model.initiate_flow_request import InitiateFlowRequest


class TestInitiateFlowRequest(unittest.TestCase):
    """InitiateFlowRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInitiateFlowRequest(self):
        """Test InitiateFlowRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InitiateFlowRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
