"""
    SigniFlow OpenAPI Spec v1

    ## SigniFlow API used to automate esignature workflow creation and management.   # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@signiflow.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import SigniFlowconnect
from SigniFlowconnect.model.get_document_tag_field_box_position_response_document_tag_fields_box_position_field import GetDocumentTagFieldBoxPositionResponseDocumentTagFieldsBoxPositionField


class TestGetDocumentTagFieldBoxPositionResponseDocumentTagFieldsBoxPositionField(unittest.TestCase):
    """GetDocumentTagFieldBoxPositionResponseDocumentTagFieldsBoxPositionField unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetDocumentTagFieldBoxPositionResponseDocumentTagFieldsBoxPositionField(self):
        """Test GetDocumentTagFieldBoxPositionResponseDocumentTagFieldsBoxPositionField"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetDocumentTagFieldBoxPositionResponseDocumentTagFieldsBoxPositionField()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
