"""
    SigniFlow OpenAPI Spec v1

    ## SigniFlow API used to automate esignature workflow creation and management.   # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@signiflow.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import SigniFlowconnect
from SigniFlowconnect.api.templates_api import TemplatesApi  # noqa: E501


class TestTemplatesApi(unittest.TestCase):
    """TemplatesApi unit test stubs"""

    def setUp(self):
        self.api = TemplatesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_post_apply_prepper_template(self):
        """Test case for post_apply_prepper_template

        Apply a Prepper template  # noqa: E501
        """
        pass

    def test_post_get_document_tag_field_box_position(self):
        """Test case for post_get_document_tag_field_box_position

        Get Document Tag Field Box Position  # noqa: E501
        """
        pass

    def test_post_get_document_tag_field_position(self):
        """Test case for post_get_document_tag_field_position

        Get Document Tag Field Position  # noqa: E501
        """
        pass

    def test_post_get_prepper_template(self):
        """Test case for post_get_prepper_template

        Get Prepper Template  # noqa: E501
        """
        pass

    def test_post_get_prepper_template_list(self):
        """Test case for post_get_prepper_template_list

        Get Prepper Template List  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
