"""
    SigniFlow OpenAPI Spec v1

    ## SigniFlow API used to automate esignature workflow creation and management.   # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@signiflow.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import SigniFlowconnect
from SigniFlowconnect.model.token_field import TokenField
globals()['TokenField'] = TokenField
from SigniFlowconnect.model.initiate_flow_no_initial_email_request import InitiateFlowNoInitialEmailRequest


class TestInitiateFlowNoInitialEmailRequest(unittest.TestCase):
    """InitiateFlowNoInitialEmailRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInitiateFlowNoInitialEmailRequest(self):
        """Test InitiateFlowNoInitialEmailRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InitiateFlowNoInitialEmailRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
