"""
    SigniFlow OpenAPI Spec v1

    ## SigniFlow API used to automate esignature workflow creation and management.   # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@signiflow.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import SigniFlowconnect
from SigniFlowconnect.model.multiple_signers_signing_ceremony_request_signer_list_field import MultipleSignersSigningCeremonyRequestSignerListField
globals()['MultipleSignersSigningCeremonyRequestSignerListField'] = MultipleSignersSigningCeremonyRequestSignerListField
from SigniFlowconnect.model.multiple_signers_signing_ceremony_request import MultipleSignersSigningCeremonyRequest


class TestMultipleSignersSigningCeremonyRequest(unittest.TestCase):
    """MultipleSignersSigningCeremonyRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMultipleSignersSigningCeremonyRequest(self):
        """Test MultipleSignersSigningCeremonyRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MultipleSignersSigningCeremonyRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
