"""
    SigniFlow OpenAPI Spec v1

    ## SigniFlow API used to automate esignature workflow creation and management.   # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@signiflow.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import SigniFlowconnect
from SigniFlowconnect.model.token_field import TokenField
globals()['TokenField'] = TokenField
from SigniFlowconnect.model.token_extend_response import TokenExtendResponse


class TestTokenExtendResponse(unittest.TestCase):
    """TokenExtendResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTokenExtendResponse(self):
        """Test TokenExtendResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TokenExtendResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
