"""
    SigniFlow OpenAPI Spec v1

    ## SigniFlow API used to automate esignature workflow creation and management.   # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@signiflow.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import SigniFlowconnect
from SigniFlowconnect.model.doc_prepper_add_advanced_fields_request_field_info_list_field import DocPrepperAddAdvancedFieldsRequestFieldInfoListField
from SigniFlowconnect.model.token_field import TokenField
globals()['DocPrepperAddAdvancedFieldsRequestFieldInfoListField'] = DocPrepperAddAdvancedFieldsRequestFieldInfoListField
globals()['TokenField'] = TokenField
from SigniFlowconnect.model.doc_prepper_add_advanced_fields_request import DocPrepperAddAdvancedFieldsRequest


class TestDocPrepperAddAdvancedFieldsRequest(unittest.TestCase):
    """DocPrepperAddAdvancedFieldsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDocPrepperAddAdvancedFieldsRequest(self):
        """Test DocPrepperAddAdvancedFieldsRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DocPrepperAddAdvancedFieldsRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
