"""
    SigniFlow OpenAPI Spec v1

    ## SigniFlow API used to automate esignature workflow creation and management.   # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@signiflow.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import SigniFlowconnect
from SigniFlowconnect.model.field_type import FieldType
globals()['FieldType'] = FieldType
from SigniFlowconnect.model.doc_prepper_add_fields_flow_id_response import DocPrepperAddFieldsFlowIDResponse


class TestDocPrepperAddFieldsFlowIDResponse(unittest.TestCase):
    """DocPrepperAddFieldsFlowIDResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDocPrepperAddFieldsFlowIDResponse(self):
        """Test DocPrepperAddFieldsFlowIDResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DocPrepperAddFieldsFlowIDResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
