"""
    SigniFlow OpenAPI Spec v1

    ## SigniFlow API used to automate esignature workflow creation and management.   # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@signiflow.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import SigniFlowconnect
from SigniFlowconnect.model.signing_ceremony_v2_response import SigningCeremonyV2Response


class TestSigningCeremonyV2Response(unittest.TestCase):
    """SigningCeremonyV2Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSigningCeremonyV2Response(self):
        """Test SigningCeremonyV2Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SigningCeremonyV2Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
