"""
    SigniFlow OpenAPI Spec v1

    ## SigniFlow API used to automate esignature workflow creation and management.   # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@signiflow.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import SigniFlowconnect
from SigniFlowconnect.model.auto_remind import AutoRemind
from SigniFlowconnect.model.doc_extension import DocExtension
from SigniFlowconnect.model.full_workflow_request_portfolio_information_field import FullWorkflowRequestPortfolioInformationField
from SigniFlowconnect.model.full_workflow_request_workflow_users_list_field import FullWorkflowRequestWorkflowUsersListField
from SigniFlowconnect.model.token_field import TokenField
globals()['AutoRemind'] = AutoRemind
globals()['DocExtension'] = DocExtension
globals()['FullWorkflowRequestPortfolioInformationField'] = FullWorkflowRequestPortfolioInformationField
globals()['FullWorkflowRequestWorkflowUsersListField'] = FullWorkflowRequestWorkflowUsersListField
globals()['TokenField'] = TokenField
from SigniFlowconnect.model.full_workflow_request import FullWorkflowRequest


class TestFullWorkflowRequest(unittest.TestCase):
    """FullWorkflowRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFullWorkflowRequest(self):
        """Test FullWorkflowRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FullWorkflowRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
