"""
    SigniFlow OpenAPI Spec v1

    ## SigniFlow API used to automate esignature workflow creation and management.   # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@signiflow.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import SigniFlowconnect
from SigniFlowconnect.model.signing_ceremony_v2_request import SigningCeremonyV2Request


class TestSigningCeremonyV2Request(unittest.TestCase):
    """SigningCeremonyV2Request unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSigningCeremonyV2Request(self):
        """Test SigningCeremonyV2Request"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SigningCeremonyV2Request()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
