"""
    SigniFlow OpenAPI Spec v1

    ## SigniFlow API used to automate esignature workflow creation and management.   # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@signiflow.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import SigniFlowconnect
from SigniFlowconnect.model.get_prepper_template_list_response_template_information_values_field import GetPrepperTemplateListResponseTemplateInformationValuesField
globals()['GetPrepperTemplateListResponseTemplateInformationValuesField'] = GetPrepperTemplateListResponseTemplateInformationValuesField
from SigniFlowconnect.model.get_prepper_template_list_response import GetPrepperTemplateListResponse


class TestGetPrepperTemplateListResponse(unittest.TestCase):
    """GetPrepperTemplateListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetPrepperTemplateListResponse(self):
        """Test GetPrepperTemplateListResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetPrepperTemplateListResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
