"""
    SigniFlow OpenAPI Spec v1

    ## SigniFlow API used to automate esignature workflow creation and management.   # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@signiflow.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import SigniFlowconnect
from SigniFlowconnect.model.full_workflow_request_group_step_field import FullWorkflowRequestGroupStepField
from SigniFlowconnect.model.full_workflow_request_workflow_user_fields_field import FullWorkflowRequestWorkflowUserFieldsField
globals()['FullWorkflowRequestGroupStepField'] = FullWorkflowRequestGroupStepField
globals()['FullWorkflowRequestWorkflowUserFieldsField'] = FullWorkflowRequestWorkflowUserFieldsField
from SigniFlowconnect.model.full_workflow_request_workflow_users_list_field import FullWorkflowRequestWorkflowUsersListField


class TestFullWorkflowRequestWorkflowUsersListField(unittest.TestCase):
    """FullWorkflowRequestWorkflowUsersListField unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFullWorkflowRequestWorkflowUsersListField(self):
        """Test FullWorkflowRequestWorkflowUsersListField"""
        # FIXME: construct object with mandatory attributes with example values
        # model = FullWorkflowRequestWorkflowUsersListField()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
