"""
    SigniFlow OpenAPI Spec v1

    ## SigniFlow API used to automate esignature workflow creation and management.   # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@signiflow.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import SigniFlowconnect
from SigniFlowconnect.model.get_prepper_template_list_response_template_information_values_field import GetPrepperTemplateListResponseTemplateInformationValuesField


class TestGetPrepperTemplateListResponseTemplateInformationValuesField(unittest.TestCase):
    """GetPrepperTemplateListResponseTemplateInformationValuesField unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetPrepperTemplateListResponseTemplateInformationValuesField(self):
        """Test GetPrepperTemplateListResponseTemplateInformationValuesField"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetPrepperTemplateListResponseTemplateInformationValuesField()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
