"""
    SigniFlow OpenAPI Spec v1

    ## SigniFlow API used to automate esignature workflow creation and management.   # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@signiflow.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import SigniFlowconnect
from SigniFlowconnect.model.get_prepper_template_response_prepper_template_values_field import GetPrepperTemplateResponsePrepperTemplateValuesField


class TestGetPrepperTemplateResponsePrepperTemplateValuesField(unittest.TestCase):
    """GetPrepperTemplateResponsePrepperTemplateValuesField unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetPrepperTemplateResponsePrepperTemplateValuesField(self):
        """Test GetPrepperTemplateResponsePrepperTemplateValuesField"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetPrepperTemplateResponsePrepperTemplateValuesField()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
