"""
    SigniFlow OpenAPI Spec v1

    ## SigniFlow API used to automate esignature workflow creation and management.   # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@signiflow.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import SigniFlowconnect
from SigniFlowconnect.model.field_type import FieldType
from SigniFlowconnect.model.token_field import TokenField
globals()['FieldType'] = FieldType
globals()['TokenField'] = TokenField
from SigniFlowconnect.model.doc_prepper_add_fields_flow_id_request import DocPrepperAddFieldsFlowIDRequest


class TestDocPrepperAddFieldsFlowIDRequest(unittest.TestCase):
    """DocPrepperAddFieldsFlowIDRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDocPrepperAddFieldsFlowIDRequest(self):
        """Test DocPrepperAddFieldsFlowIDRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DocPrepperAddFieldsFlowIDRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
