"""
    SigniFlow OpenAPI Spec v1

    ## SigniFlow API used to automate esignature workflow creation and management.   # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@signiflow.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import SigniFlowconnect
from SigniFlowconnect.model.get_document_audit_response_activity_field import GetDocumentAuditResponseActivityField
globals()['GetDocumentAuditResponseActivityField'] = GetDocumentAuditResponseActivityField
from SigniFlowconnect.model.get_document_audit_response import GetDocumentAuditResponse


class TestGetDocumentAuditResponse(unittest.TestCase):
    """GetDocumentAuditResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetDocumentAuditResponse(self):
        """Test GetDocumentAuditResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetDocumentAuditResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
