"""
    SigniFlow OpenAPI Spec v1

    ## SigniFlow API used to automate esignature workflow creation and management.   # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@signiflow.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import SigniFlowconnect
from SigniFlowconnect.model.get_document_tag_field_position_response_document_tag_fields_position_field import GetDocumentTagFieldPositionResponseDocumentTagFieldsPositionField


class TestGetDocumentTagFieldPositionResponseDocumentTagFieldsPositionField(unittest.TestCase):
    """GetDocumentTagFieldPositionResponseDocumentTagFieldsPositionField unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetDocumentTagFieldPositionResponseDocumentTagFieldsPositionField(self):
        """Test GetDocumentTagFieldPositionResponseDocumentTagFieldsPositionField"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetDocumentTagFieldPositionResponseDocumentTagFieldsPositionField()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
