"""
    SigniFlow OpenAPI Spec v1

    ## SigniFlow API used to automate esignature workflow creation and management.   # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@signiflow.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import SigniFlowconnect
from SigniFlowconnect.model.advanced_field_type import AdvancedFieldType
from SigniFlowconnect.model.doc_prepper_add_advanced_fields_request_field_options_list_field import DocPrepperAddAdvancedFieldsRequestFieldOptionsListField
globals()['AdvancedFieldType'] = AdvancedFieldType
globals()['DocPrepperAddAdvancedFieldsRequestFieldOptionsListField'] = DocPrepperAddAdvancedFieldsRequestFieldOptionsListField
from SigniFlowconnect.model.doc_prepper_add_advanced_fields_request_field_info_list_field import DocPrepperAddAdvancedFieldsRequestFieldInfoListField


class TestDocPrepperAddAdvancedFieldsRequestFieldInfoListField(unittest.TestCase):
    """DocPrepperAddAdvancedFieldsRequestFieldInfoListField unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDocPrepperAddAdvancedFieldsRequestFieldInfoListField(self):
        """Test DocPrepperAddAdvancedFieldsRequestFieldInfoListField"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DocPrepperAddAdvancedFieldsRequestFieldInfoListField()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
