"""
    SigniFlow OpenAPI Spec v1

    ## SigniFlow API used to automate esignature workflow creation and management.   # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@signiflow.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import SigniFlowconnect
from SigniFlowconnect.model.action_field import ActionField


class TestActionField(unittest.TestCase):
    """ActionField unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testActionField(self):
        """Test ActionField"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ActionField()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
