"""
    SigniFlow OpenAPI Spec v1

    ## SigniFlow API used to automate esignature workflow creation and management.   # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@signiflow.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import SigniFlowconnect
from SigniFlowconnect.model.cancel_flow_response import CancelFlowResponse


class TestCancelFlowResponse(unittest.TestCase):
    """CancelFlowResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCancelFlowResponse(self):
        """Test CancelFlowResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CancelFlowResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
