"""
    SigniFlow OpenAPI Spec v1

    ## SigniFlow API used to automate esignature workflow creation and management.   # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@signiflow.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import SigniFlowconnect
from SigniFlowconnect.api.work_flow_api import WorkFlowApi  # noqa: E501


class TestWorkFlowApi(unittest.TestCase):
    """WorkFlowApi unit test stubs"""

    def setUp(self):
        self.api = WorkFlowApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_workflow(self):
        """Test case for create_workflow

        Create Workflow  # noqa: E501
        """
        pass

    def test_get_document(self):
        """Test case for get_document

        Get Document  # noqa: E501
        """
        pass

    def test_post_add_workflow_step(self):
        """Test case for post_add_workflow_step

        Add a Workflow step  # noqa: E501
        """
        pass

    def test_post_cancel_flow(self):
        """Test case for post_cancel_flow

        Cancel Flow  # noqa: E501
        """
        pass

    def test_post_delete_doc(self):
        """Test case for post_delete_doc

        Delete Document  # noqa: E501
        """
        pass

    def test_post_doc_prepper_add_field(self):
        """Test case for post_doc_prepper_add_field

        Document Prepper Add Fields  # noqa: E501
        """
        pass

    def test_post_doc_prepper_advanced_fields(self):
        """Test case for post_doc_prepper_advanced_fields

        Document Prepper Add Advanced Fields  # noqa: E501
        """
        pass

    def test_post_full_workflow(self):
        """Test case for post_full_workflow

        FullWorkflow  # noqa: E501
        """
        pass

    def test_post_get_doc_status(self):
        """Test case for post_get_doc_status

        Get Document Status  # noqa: E501
        """
        pass

    def test_post_initiate_flow(self):
        """Test case for post_initiate_flow

        Initiate Flow  # noqa: E501
        """
        pass

    def test_post_initiate_flow_no_email(self):
        """Test case for post_initiate_flow_no_email

        Initiate Flow No Email  # noqa: E501
        """
        pass

    def test_post_initiate_flow_no_initial_email(self):
        """Test case for post_initiate_flow_no_initial_email

        Initiate Flow No Initial Email  # noqa: E501
        """
        pass

    def test_post_workflow_sign(self):
        """Test case for post_workflow_sign

        Workflow Sign  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
