"""
    SigniFlow OpenAPI Spec v1

    ## SigniFlow API used to automate esignature workflow creation and management.   # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@signiflow.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import SigniFlowconnect
from SigniFlowconnect.model.initiate_flow_no_initial_email_response import InitiateFlowNoInitialEmailResponse


class TestInitiateFlowNoInitialEmailResponse(unittest.TestCase):
    """InitiateFlowNoInitialEmailResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInitiateFlowNoInitialEmailResponse(self):
        """Test InitiateFlowNoInitialEmailResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InitiateFlowNoInitialEmailResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
