"""
    SigniFlow OpenAPI Spec v1

    ## SigniFlow API used to automate esignature workflow creation and management.   # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@signiflow.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import SigniFlowconnect
from SigniFlowconnect.api.portfolios_api import PortfoliosApi  # noqa: E501


class TestPortfoliosApi(unittest.TestCase):
    """PortfoliosApi unit test stubs"""

    def setUp(self):
        self.api = PortfoliosApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_post_create_portfolio(self):
        """Test case for post_create_portfolio

        Create Portfolio  # noqa: E501
        """
        pass

    def test_post_download_portfolio(self):
        """Test case for post_download_portfolio

        Download Portfolio  # noqa: E501
        """
        pass

    def test_post_link_to_portfolio(self):
        """Test case for post_link_to_portfolio

        Link To Portfolio  # noqa: E501
        """
        pass

    def test_post_set_document_order(self):
        """Test case for post_set_document_order

        Set Document Order  # noqa: E501
        """
        pass

    def test_post_share_portfolio(self):
        """Test case for post_share_portfolio

        Share Portfolio  # noqa: E501
        """
        pass

    def test_post_share_portfolio_no_email(self):
        """Test case for post_share_portfolio_no_email

        Share Portfolio No Email  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
