"""
    SigniFlow OpenAPI Spec v1

    ## SigniFlow API used to automate esignature workflow creation and management.   # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@signiflow.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import SigniFlowconnect
from SigniFlowconnect.api.authentication_api import AuthenticationApi  # noqa: E501


class TestAuthenticationApi(unittest.TestCase):
    """AuthenticationApi unit test stubs"""

    def setUp(self):
        self.api = AuthenticationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_login(self):
        """Test case for login

        Login  # noqa: E501
        """
        pass

    def test_post_logout(self):
        """Test case for post_logout

        Logout  # noqa: E501
        """
        pass

    def test_post_token_extend(self):
        """Test case for post_token_extend

        Token Extend  # noqa: E501
        """
        pass

    def test_post_token_validate(self):
        """Test case for post_token_validate

        Token Validate  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
