"""
    SigniFlow OpenAPI Spec v1

    ## SigniFlow API used to automate esignature workflow creation and management.   # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@signiflow.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import SigniFlowconnect
from SigniFlowconnect.model.get_document_tag_field_position_response_document_tag_fields_position_field import GetDocumentTagFieldPositionResponseDocumentTagFieldsPositionField
globals()['GetDocumentTagFieldPositionResponseDocumentTagFieldsPositionField'] = GetDocumentTagFieldPositionResponseDocumentTagFieldsPositionField
from SigniFlowconnect.model.get_document_tag_field_position_response import GetDocumentTagFieldPositionResponse


class TestGetDocumentTagFieldPositionResponse(unittest.TestCase):
    """GetDocumentTagFieldPositionResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetDocumentTagFieldPositionResponse(self):
        """Test GetDocumentTagFieldPositionResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetDocumentTagFieldPositionResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
