"""
    SigniFlow OpenAPI Spec v1

    ## SigniFlow API used to automate esignature workflow creation and management.   # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@signiflow.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import SigniFlowconnect
from SigniFlowconnect.api.viewers_api import ViewersApi  # noqa: E501


class TestViewersApi(unittest.TestCase):
    """ViewersApi unit test stubs"""

    def setUp(self):
        self.api = ViewersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_post_get_doc_link(self):
        """Test case for post_get_doc_link

        Get Document Link  # noqa: E501
        """
        pass

    def test_post_get_document_prepper_link(self):
        """Test case for post_get_document_prepper_link

        Get Document Prepper Link  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
