"""
    SigniFlow OpenAPI Spec v1

    ## SigniFlow API used to automate esignature workflow creation and management.   # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@signiflow.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import SigniFlowconnect
from SigniFlowconnect.model.doc_prepper_add_advanced_fields_response_advanced_field_response_list_field import DocPrepperAddAdvancedFieldsResponseAdvancedFieldResponseListField


class TestDocPrepperAddAdvancedFieldsResponseAdvancedFieldResponseListField(unittest.TestCase):
    """DocPrepperAddAdvancedFieldsResponseAdvancedFieldResponseListField unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDocPrepperAddAdvancedFieldsResponseAdvancedFieldResponseListField(self):
        """Test DocPrepperAddAdvancedFieldsResponseAdvancedFieldResponseListField"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DocPrepperAddAdvancedFieldsResponseAdvancedFieldResponseListField()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
