"""
    SigniFlow OpenAPI Spec v1

    ## SigniFlow API used to automate esignature workflow creation and management.   # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@signiflow.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import SigniFlowconnect
from SigniFlowconnect.model.doc_prepper_add_advanced_fields_request_field_options_list_field import DocPrepperAddAdvancedFieldsRequestFieldOptionsListField


class TestDocPrepperAddAdvancedFieldsRequestFieldOptionsListField(unittest.TestCase):
    """DocPrepperAddAdvancedFieldsRequestFieldOptionsListField unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDocPrepperAddAdvancedFieldsRequestFieldOptionsListField(self):
        """Test DocPrepperAddAdvancedFieldsRequestFieldOptionsListField"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DocPrepperAddAdvancedFieldsRequestFieldOptionsListField()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
