"""
    SigniFlow OpenAPI Spec v1

    ## SigniFlow API used to automate esignature workflow creation and management.   # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@signiflow.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import SigniFlowconnect
from SigniFlowconnect.model.logout_request import LogoutRequest


class TestLogoutRequest(unittest.TestCase):
    """LogoutRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLogoutRequest(self):
        """Test LogoutRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LogoutRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
