"""
    SigniFlow OpenAPI Spec v1

    ## SigniFlow API used to automate esignature workflow creation and management.   # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@signiflow.com
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from SigniFlowconnect.api_client import ApiClient, Endpoint as _Endpoint
from SigniFlowconnect.model_utils import (  # noqa: F401
    check_allowed_values,
    check_validations,
    date,
    datetime,
    file_type,
    none_type,
    validate_and_convert_types
)
from SigniFlowconnect.model.apply_prepper_template_request import ApplyPrepperTemplateRequest
from SigniFlowconnect.model.apply_prepper_template_response import ApplyPrepperTemplateResponse
from SigniFlowconnect.model.get_document_tag_field_box_position_request import GetDocumentTagFieldBoxPositionRequest
from SigniFlowconnect.model.get_document_tag_field_box_position_response import GetDocumentTagFieldBoxPositionResponse
from SigniFlowconnect.model.get_document_tag_field_position_request import GetDocumentTagFieldPositionRequest
from SigniFlowconnect.model.get_document_tag_field_position_response import GetDocumentTagFieldPositionResponse
from SigniFlowconnect.model.get_prepper_template_list_request import GetPrepperTemplateListRequest
from SigniFlowconnect.model.get_prepper_template_list_response import GetPrepperTemplateListResponse
from SigniFlowconnect.model.get_prepper_template_request import GetPrepperTemplateRequest
from SigniFlowconnect.model.get_prepper_template_response import GetPrepperTemplateResponse


class TemplatesApi(object):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

        def __post_apply_prepper_template(
            self,
            content_type="application/json",
            **kwargs
        ):
            """Apply a Prepper template  # noqa: E501

            #### Used when applying a templaet to a document.  # noqa: E501
            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.post_apply_prepper_template(content_type="application/json", async_req=True)
            >>> result = thread.get()

            Args:
                content_type (str): defaults to "application/json", must be one of ["application/json"]

            Keyword Args:
                apply_prepper_template_request (ApplyPrepperTemplateRequest): ##### Apply A Prepper Template Request Model. [optional]
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                ApplyPrepperTemplateResponse
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['content_type'] = \
                content_type
            return self.call_with_http_info(**kwargs)

        self.post_apply_prepper_template = _Endpoint(
            settings={
                'response_type': (ApplyPrepperTemplateResponse,),
                'auth': [],
                'endpoint_path': '/ApplyPrepperTemplate',
                'operation_id': 'post_apply_prepper_template',
                'http_method': 'POST',
                'servers': None,
            },
            params_map={
                'all': [
                    'content_type',
                    'apply_prepper_template_request',
                ],
                'required': [
                    'content_type',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'content_type':
                        (str,),
                    'apply_prepper_template_request':
                        (ApplyPrepperTemplateRequest,),
                },
                'attribute_map': {
                    'content_type': 'Content-Type',
                },
                'location_map': {
                    'content_type': 'header',
                    'apply_prepper_template_request': 'body',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [
                    'application/json'
                ]
            },
            api_client=api_client,
            callable=__post_apply_prepper_template
        )

        def __post_get_document_tag_field_box_position(
            self,
            content_type="application/json",
            **kwargs
        ):
            """Get Document Tag Field Box Position  # noqa: E501

            #### Used to get the tag field box position on a document.  # noqa: E501
            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.post_get_document_tag_field_box_position(content_type="application/json", async_req=True)
            >>> result = thread.get()

            Args:
                content_type (str): defaults to "application/json", must be one of ["application/json"]

            Keyword Args:
                get_document_tag_field_box_position_request (GetDocumentTagFieldBoxPositionRequest): ##### Get Document Tag Field Box Position Request Model. [optional]
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                GetDocumentTagFieldBoxPositionResponse
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['content_type'] = \
                content_type
            return self.call_with_http_info(**kwargs)

        self.post_get_document_tag_field_box_position = _Endpoint(
            settings={
                'response_type': (GetDocumentTagFieldBoxPositionResponse,),
                'auth': [],
                'endpoint_path': '/GetDocumentTagFieldBoxPosition',
                'operation_id': 'post_get_document_tag_field_box_position',
                'http_method': 'POST',
                'servers': None,
            },
            params_map={
                'all': [
                    'content_type',
                    'get_document_tag_field_box_position_request',
                ],
                'required': [
                    'content_type',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'content_type':
                        (str,),
                    'get_document_tag_field_box_position_request':
                        (GetDocumentTagFieldBoxPositionRequest,),
                },
                'attribute_map': {
                    'content_type': 'Content-Type',
                },
                'location_map': {
                    'content_type': 'header',
                    'get_document_tag_field_box_position_request': 'body',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [
                    'application/json'
                ]
            },
            api_client=api_client,
            callable=__post_get_document_tag_field_box_position
        )

        def __post_get_document_tag_field_position(
            self,
            content_type="application/json",
            **kwargs
        ):
            """Get Document Tag Field Position  # noqa: E501

            #### Used to get the tag position on a document.  # noqa: E501
            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.post_get_document_tag_field_position(content_type="application/json", async_req=True)
            >>> result = thread.get()

            Args:
                content_type (str): defaults to "application/json", must be one of ["application/json"]

            Keyword Args:
                get_document_tag_field_position_request (GetDocumentTagFieldPositionRequest): ##### Get Document Tag Field Position Request Model. [optional]
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                GetDocumentTagFieldPositionResponse
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['content_type'] = \
                content_type
            return self.call_with_http_info(**kwargs)

        self.post_get_document_tag_field_position = _Endpoint(
            settings={
                'response_type': (GetDocumentTagFieldPositionResponse,),
                'auth': [],
                'endpoint_path': '/GetDocumentTagFieldPosition',
                'operation_id': 'post_get_document_tag_field_position',
                'http_method': 'POST',
                'servers': None,
            },
            params_map={
                'all': [
                    'content_type',
                    'get_document_tag_field_position_request',
                ],
                'required': [
                    'content_type',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'content_type':
                        (str,),
                    'get_document_tag_field_position_request':
                        (GetDocumentTagFieldPositionRequest,),
                },
                'attribute_map': {
                    'content_type': 'Content-Type',
                },
                'location_map': {
                    'content_type': 'header',
                    'get_document_tag_field_position_request': 'body',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [
                    'application/json'
                ]
            },
            api_client=api_client,
            callable=__post_get_document_tag_field_position
        )

        def __post_get_prepper_template(
            self,
            content_type="application/json",
            **kwargs
        ):
            """Get Prepper Template  # noqa: E501

            #### Used to get a document template.  # noqa: E501
            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.post_get_prepper_template(content_type="application/json", async_req=True)
            >>> result = thread.get()

            Args:
                content_type (str): defaults to "application/json", must be one of ["application/json"]

            Keyword Args:
                get_prepper_template_request (GetPrepperTemplateRequest): ##### Get Prepper Template Request Model. [optional]
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                GetPrepperTemplateResponse
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['content_type'] = \
                content_type
            return self.call_with_http_info(**kwargs)

        self.post_get_prepper_template = _Endpoint(
            settings={
                'response_type': (GetPrepperTemplateResponse,),
                'auth': [],
                'endpoint_path': '/GetPrepperTemplate',
                'operation_id': 'post_get_prepper_template',
                'http_method': 'POST',
                'servers': None,
            },
            params_map={
                'all': [
                    'content_type',
                    'get_prepper_template_request',
                ],
                'required': [
                    'content_type',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'content_type':
                        (str,),
                    'get_prepper_template_request':
                        (GetPrepperTemplateRequest,),
                },
                'attribute_map': {
                    'content_type': 'Content-Type',
                },
                'location_map': {
                    'content_type': 'header',
                    'get_prepper_template_request': 'body',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [
                    'application/json'
                ]
            },
            api_client=api_client,
            callable=__post_get_prepper_template
        )

        def __post_get_prepper_template_list(
            self,
            content_type="application/json",
            **kwargs
        ):
            """Get Prepper Template List  # noqa: E501

            #### Used to get a list of document templates.  # noqa: E501
            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.post_get_prepper_template_list(content_type="application/json", async_req=True)
            >>> result = thread.get()

            Args:
                content_type (str): defaults to "application/json", must be one of ["application/json"]

            Keyword Args:
                get_prepper_template_list_request (GetPrepperTemplateListRequest): ##### Get Prepper Template List Request Model. [optional]
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (float/tuple): timeout setting for this request. If one
                    number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                GetPrepperTemplateListResponse
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['content_type'] = \
                content_type
            return self.call_with_http_info(**kwargs)

        self.post_get_prepper_template_list = _Endpoint(
            settings={
                'response_type': (GetPrepperTemplateListResponse,),
                'auth': [],
                'endpoint_path': '/GetPrepperTemplateList',
                'operation_id': 'post_get_prepper_template_list',
                'http_method': 'POST',
                'servers': None,
            },
            params_map={
                'all': [
                    'content_type',
                    'get_prepper_template_list_request',
                ],
                'required': [
                    'content_type',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'content_type':
                        (str,),
                    'get_prepper_template_list_request':
                        (GetPrepperTemplateListRequest,),
                },
                'attribute_map': {
                    'content_type': 'Content-Type',
                },
                'location_map': {
                    'content_type': 'header',
                    'get_prepper_template_list_request': 'body',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [
                    'application/json'
                ]
            },
            api_client=api_client,
            callable=__post_get_prepper_template_list
        )
